import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

// Utility to convert JSON array to CSV string
function jsonToCsv(items: any[]) {
  if (items.length === 0) return "";

  const headers = Object.keys(items[0]);
  const csvRows = [];

  // Add headers
  csvRows.push(headers.map(h => `"${h.replace(/"/g, '""')}"`).join(","));

  // Add rows
  for (const item of items) {
    const values = headers.map(header => {
      const val = item[header];
      const strVal = val === null || val === undefined ? "" : String(val);
      // Escape double quotes and wrap in quotes
      return `"${strVal.replace(/"/g, '""')}"`;
    });
    csvRows.push(values.join(","));
  }

  return csvRows.join("\n");
}

export async function GET(request: Request) {
  try {
    const session = await auth();
    if (!session?.user) {
      return new NextResponse("Unauthorized", { status: 403 });
    }

    const { searchParams } = new URL(request.url);
    const type = searchParams.get("type"); // e.g., 'students', 'elections', 'audit'
    const departmentId = searchParams.get("departmentId");
    const statusFilter = searchParams.get("status");
    const searchFilter = searchParams.get("search");

    // RBAC Check
    if (session.user.role === "STUDENT") {
      return new NextResponse("Forbidden", { status: 403 });
    }

    if (session.user.role === "DEPARTMENT_ADMIN") {
      if (departmentId && departmentId !== session.user.departmentId) {
         return new NextResponse("Forbidden", { status: 403 });
      }
    }

    const targetDeptId = session.user.role === "DEPARTMENT_ADMIN" ? session.user.departmentId : departmentId;
    let data: any[] = [];
    const filename = `report_${type}_${new Date().toISOString().split('T')[0]}.csv`;

    if (type === "students") {
      const students = await prisma.student.findMany({
        where: {
          ...(targetDeptId ? { departmentId: targetDeptId } : {}),
          ...(statusFilter ? { status: statusFilter as any } : {}),
          ...(searchFilter ? {
            OR: [
              { matricNo: { contains: searchFilter, mode: 'insensitive' } },
              { fullName: { contains: searchFilter, mode: 'insensitive' } },
              { email: { contains: searchFilter, mode: 'insensitive' } }
            ]
          } : {})
        },
        include: { department: true }
      });
      data = students.map(s => ({
        Matric_No: s.matricNo,
        Full_Name: s.fullName,
        Email: s.email,
        Level: s.level,
        Status: s.status,
        Eligible: s.isEligible ? "Yes" : "No",
        Department: s.department.code
      }));
    } else if (type === "elections") {
      const elections = await prisma.election.findMany({
        where: {
          ...(targetDeptId ? { departmentId: targetDeptId } : {}),
          ...(statusFilter ? { status: statusFilter as any } : {}),
          ...(searchFilter ? { title: { contains: searchFilter, mode: 'insensitive' } } : {})
        },
        include: { department: true }
      });
      data = elections.map(e => ({
        Title: e.title,
        Status: e.status,
        Department: e.department.code,
        Start_Time: e.startTime?.toISOString() || "",
        End_Time: e.endTime?.toISOString() || ""
      }));
    } else if (type === "audit" && session.user.role === "SUPER_ADMIN") {
      const logs = await prisma.auditLog.findMany({
        include: { user: true },
        orderBy: { createdAt: 'desc' },
        take: 1000 // Limit for safety
      });
      data = logs.map(l => ({
        Timestamp: l.createdAt.toISOString(),
        User: l.user?.email || "System",
        Action: l.action,
        Entity: l.entity || "",
        Entity_ID: l.entityId || "",
        IP_Address: l.ipAddress || ""
      }));
    } else {
      return new NextResponse("Invalid report type or insufficient permissions", { status: 400 });
    }

    const csvData = jsonToCsv(data);

    // Ensure we include metadata as required by VM rules (Native CSV)
    const metadata = `"Report Type: ${type}","Generated Date: ${new Date().toISOString()}","Generated By: ${session.user.email}","Filters Applied: Status=${statusFilter || 'All'}, Search=${searchFilter || 'None'}"\n\n`;

    return new NextResponse(metadata + csvData, {
      status: 200,
      headers: {
        "Content-Type": "text/csv; charset=utf-8",
        "Content-Disposition": `attachment; filename="${filename}"`
      }
    });

  } catch (error) {
    console.error("Export Error:", error);
    return new NextResponse("Internal Server Error", { status: 500 });
  }
}
