export enum Roles {
  SUPER_ADMIN = "SUPER_ADMIN",
  DEPARTMENT_ADMIN = "DEPARTMENT_ADMIN",
  STUDENT = "STUDENT",
}

export const Routes = {
  HOME: "/",
  LOGIN: "/login",
  ONBOARDING: "/onboarding",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",
  DEPARTMENTS: "/departments",
  ELECTIONS: "/elections",
  STUDENTS: "/students",
  USERS: "/users",
  CANDIDATES: "/candidates",
  CANDIDATE_APPROVALS: "/candidates/approvals",
  candidateProfile: (id: string) => `/candidates/${id}` as const,
  VOTING: "/vote",
  RESULTS: "/results",
  REPORTS: "/reports",
  NOTIFICATIONS: "/notifications",
  AUDIT_LOGS: "/audit-logs",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  ANNOUNCEMENTS: "/announcements",
  ACTIVITY: "/activity",
};
